# Generated by Django 4.1 on 2022-08-14 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_year', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.album')),
            ],
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyric', models.CharField(max_length=100)),
                ('order', models.SmallIntegerField(default=1)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.song')),
            ],
        ),
    ]
